{
  "src/django_integrity/constraints.py": {
    "Module has no attribute \"transaction\"  [attr-defined]": 4
  },
  "src/django_integrity/conversion.py": {
    "Argument 1 to \"match\" of \"Pattern\" has incompatible type \"str | None\"; expected \"str\"  [arg-type]": 3,
    "Function is missing a return type annotation  [no-untyped-def]": 1
  },
  "tests/django_integrity/test_conversion.py": {
    "Argument \"fields\" to \"Unique\" has incompatible type \"tuple[str, str]\"; expected \"tuple[str]\"  [arg-type]": 1,
    "Argument \"model\" to \"Unique\" has incompatible type \"Unique\"; expected \"type[Model]\"  [arg-type]": 1,
    "Argument 1 to \"refine_integrity_error\" has incompatible type \"dict[ForeignKey, type[SimpleError]]\"; expected \"Mapping[_Rule, Exception]\"  [arg-type]": 3,
    "Argument 1 to \"refine_integrity_error\" has incompatible type \"dict[Named, type[SimpleError]]\"; expected \"Mapping[_Rule, Exception]\"  [arg-type]": 2,
    "Argument 1 to \"refine_integrity_error\" has incompatible type \"dict[NotNull, type[SimpleError]]\"; expected \"Mapping[_Rule, Exception]\"  [arg-type]": 3,
    "Argument 1 to \"refine_integrity_error\" has incompatible type \"dict[PrimaryKey, type[SimpleError]]\"; expected \"Mapping[_Rule, Exception]\"  [arg-type]": 2,
    "Argument 1 to \"refine_integrity_error\" has incompatible type \"dict[Unique, type[SimpleError]]\"; expected \"Mapping[_Rule, Exception]\"  [arg-type]": 3,
    "Incompatible type for \"unique_field\" of \"AlternativeUniqueModel\" (got \"None\", expected \"float | int | str | Combinable\")  [misc]": 1,
    "Incompatible type for \"unique_field\" of \"UniqueModel\" (got \"None\", expected \"float | int | str | Combinable\")  [misc]": 2
  }
}
